name: Variáveis no Workflow

on: 
  workflow_dispatch: #Disparo manual

jobs: 
  primeiro-variaveis-exemplo:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: "Olá, GitHub Actions"
    steps:
      - name: Exibir Váriavel local
        run: echo "A variável contém:" $MY_VARIABLE

  segundo-variaveis-exemplo:
    runs-on: ubuntu-latest
    needs: [primeiro-variaveis-exemplo]
    steps:
      - name: Exibir Váriavel local
        run: echo "A variável contém:" $MY_VARIABLE
  